### PR TITLE
Add NTv2 grid for Catalonia

### PR DESCRIPTION
**Pull request by carlospsig**
Hi Giovanni,
I would to add NTv2 grid for Catalonia, region of Spain, the catalan institut cartografic have another grid better than spanish institute!
Is it possible?

Thank in advance!

Best regards,

### CODE REVIEW

**Comment by gioman** [comment]
Hi Carlos! is the ntv2 grid for Catalonia freely redistibutable? What is the source I can cite here? https://github.com/NaturalGIS/ntv2_transformations/blob/master/README.md

Cheers!

**Comment by carlospsig** [comment]
Hi Giovanni,
I asked for permision to redistributable, as soon as ICC answer my question
I'll confirm you it!

The oficial web is www.icc.cat.
The source for grid file is here:
http://www.icc.cat/eng/Home-ICC/Geodesia/Recursos

Cheers!
- http://www.psig.es*

_Carlos López Quintanilla_

www.psig.es
carlos.lopez@psig.es
+34 699.680.261

2015-07-22 1:19 GMT+02:00 Giovanni Manghi notifications@github.com:

**Comment by gioman** [comment]
Hi Carlos, the page http://www.icc.cat/eng/Home-ICC/Geodesia/Recursos seems does not say anything about possible limitations... let's go forward and add this grid/transformations to the plugin?

**Comment by carlospsig** [comment]
Hi Giovanni,
Sorry, I forgot to send you a message!!
6 days ago The ICGC sent me an email to say me that we can use de grid but
mentioning the source.

Thanks you for all!

ICGC say (in catalan):

_Bon dia._

_Podeu utilitzar el fitxer en qüestió lliurement (sempre que es faci de
forma correcta, legal, etc.), citant l’ICGC com a autor del mateix, si és
possible, especialment per si algú en necessita més informació._

_Atentament,_

_Institut Cartogràfic i Geològic de Catalunya_

_Parc de Montjuïc | 08038 Barcelona | Tel. 93 567 15 00
<93%20567%2015%2000> | Fax 93 567 15 67 <93%20567%2015%2067>_

_icgc@icgc.cat icgc@icgc.cat | www.icgc.cat
http://www.icgc.cat/ | facebook.com/ICGCat
http://www.facebook.com/ICGCat | twitter.com/ICGCat
http://twitter.com/ICGCat_

_From: carlos.lopez@psig.es
carlos.lopez@psig.es [mailto:carlos.lopez@psig.es
carlos.lopez@psig.es] Sent: dimecres, 22 / juliol / 2015
09:12To: ICGCSubject: Consulta_

_Nom i Cognoms: Carlos López Quintanilla Email: carlos.lopez@psig.es
carlos.lopez@psig.es Tema: Canvi a ETRS89 Bon dia, A qui correspongui,
volia saber el tipus de llicència del fitxer de transformació
(100800401.gsb) per fer-lo servir en un complement del programari QGIS
(www.qgis.org http://www.qgis.org/). En concret, el voelm afegir al
plugin aquest: https://github.com/NaturalGIS/ntv2_transformations
https://github.com/NaturalGIS/ntv2_transformations Atentament, Carlos
López Quintanilla Consultor SIG, PSIG carlos.lopez@psig.es
carlos.lopez@psig.es_
- http://www.psig.es*

_Carlos López Quintanilla_

www.psig.es
carlos.lopez@psig.es
+34 699.680.261

2015-08-03 10:57 GMT+02:00 Giovanni Manghi notifications@github.com:

**Pull request merged**
